site_name: Virechana Assessment App Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Folder Structure: folder_structure.md
  - API Integration: api_integration.md
  - Model: user.md
  - Screen Details:
      - Patient Details: patient_details.md
      - Purvakarma: purvakarma.md
      - Pradhana Karma: pradhana_karma.md
      - Shuddhi Assessment: shuddhi_assessment.md
      - Samyak: samyak.md
      - Ayoga: ayoga.md
      - Atiyoga: atiyoga.md
      - Post Procedure: post_procedure.md
      - Summary Page: summary.md
  - State Management:
      - Form State: form_state.md
      - Samyak State: samyak_state.md
      - Ayoga State: ayoga_state.md
      - Atiyoga State: atiyoga_state.md
  - Widgets: widgets.md
